# Generated by Django 5.2.6 on 2025-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='users.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('New', 'New'), ('Current', 'Current'), ('External', 'External')], default='Current', max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='actor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
