# Generated by Django 5.2.6 on 2025-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_permissions_user_user_status_alter_log_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_color_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_pacifica_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_wifi_other_devices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='share_drive_request',
            field=models.CharField(blank=True, help_text='เก็บชื่อ Share Drive ที่ขอ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='software_request',
            field=models.CharField(blank=True, help_text='เก็บชื่อ Software ที่ขอ', max_length=255),
        ),
    ]
